### ISSUE TITLE
Update readme.md

### ISSUE THREAD

**Issue by Anandkumar8418** [Anandkumar8418/TASK-3-Static-Site-Generator#2]
Can anyone make my readme.md file better

**Comment by Simontagbor** [comment]
> Can anyone make my readme.md file better

Hi @Anandkumar8418,  I realised the repo has no description and the readme is missing an introduction to your project.
It might be helpful for newcomers to your project.

I will try and figure out how your code works and update the readme page accordingly. cheers 🎊
